---
resources:
- name: builder-task
  type: git
  source:
    uri: https://github.com/concourse/builder-task
    branch: buildkit-spike

- name: builder-task-image
  type: registry-image
  source:
    repository: concourse/builder-task
    tag: buildkit
    username: ((docker.username))
    password: ((docker.password))

jobs:
- name: test
  plan:
  - get: builder-task
    trigger: true
  - task: test
    privileged: true
    file: builder-task/ci/tasks/test.yml

- name: publish
  plan:
  - get: builder-task
    passed: [test]
  - task: build
    file: builder-task/ci/tasks/build.yml
  - task: build-image
    privileged: true
    file: builder-task/ci/tasks/build-image.yml
  - put: builder-task-image
    params: {image: image/image.tar}
